### ISSUE TITLE
Is there a way to add logging to specific routes on express?

### ISSUE THREAD

**Issue by leocabeza** [apitally/apitally-js#25]
At the moment, I'm trying to add analytics to a router inside my express app, but it only accepts an express app:

<img width="440" alt="image" src="https://github.com/user-attachments/assets/8e4f6642-3448-457f-9d65-411170ce160c">

**Comment by leocabeza** [comment]
Update: it looks like it's still going through:

![image](https://github.com/user-attachments/assets/de12c784-d750-4157-b599-ded43c681cf9)

**Comment by itssimon** [comment]
This is a good idea. I'm going to implement support for this use case.

**Comment by itssimon** [comment]
Should be fixed in v0.8.1, which was just released.
