### ISSUE TITLE
Error 524 (Timeout) when using apitally-js on AWS instance

### ISSUE THREAD

**Issue by Charlie85270** [apitally/apitally-js#54]
Hello guys, 

I'm using you library to track metrics on my API.

When I'm working on local everything works correctly, but when I deploy my app in a AWS instance I have an issue.

My app (dev) is detected and active but I can't get any data.

<img width="304" alt="image" src="https://github.com/user-attachments/assets/e16d8001-d8de-4bee-8012-6caad9e6c34b">

Here is the issue from my sentry : 

<img width="1118" alt="Capture d’écran, le 2024-11-05 à 21 39 32" src="https://github.com/user-attachments/assets/b3da6dcf-8d2a-401e-b4e4-daefd9dafe96">

It seems that it can't reach the apitally endpoint (524). 

Do you have an idea why ? 

Let me know if you need more details

**Comment by itssimon** [comment]
Hey Charlie, is this an ongoing issue or was there just a couple of these events over the last 24 hours? I did an infrastructure upgrade earlier today, which could've caused some hub requests to time out, but the client library is designed to handle that gracefully and retry later, so no data should be lost.

Either way I don't think this is a problem with the client library, but I'm happy to help you get to the bottom of this. Would you mind jumping into our Slack channel and chat there?
